"""Centralized English UI strings for future localization."""

APP_TITLE = "HCQ — Houdini Cook Queue"
TAB_MONITOR = "Monitor"
TAB_QUEUES = "Queues"
TAB_RUN = "Run"
TAB_HISTORY = "History"
TAB_SETTINGS = "Settings"

STATUS_IDLE = "Idle"
STATUS_WATCHING = "Watching"
STATUS_COOKING = "Cooking"
STATUS_DISABLED = "Disabled"
STATUS_MISSING = "Missing"
STATUS_READY = "Ready"

ADD_SELECTED_NODES = "Add Selected Nodes"
ADD_BY_PATH = "Add by Path"
REMOVE = "Remove"
ENABLE = "Enable"
DISABLE = "Disable"
GO_TO_NODE = "Go to Node"
NEW_QUEUE = "New Queue"
EDIT = "Edit"
DUPLICATE = "Duplicate"
DELETE = "Delete"
IMPORT_JSON = "Import JSON"
EXPORT_JSON = "Export JSON"
ADD_TO_RUN_LIST = "Add to Run List"
PREFLIGHT_CHECK = "Preflight Check"
RUN_QUEUE = "Run Queue"
PAUSE_AFTER_CURRENT = "Pause After Current Job"
RESUME = "Resume"
CANCEL_CURRENT = "Cancel Current Cook"

NO_SELECTION = "Nothing is selected."
UNSUPPORTED_ENVIRONMENT = "HCQ requires Houdini 21.0 or later on Windows."
QUEUE_ALREADY_RUNNING = "Another HCQ run session is already active."
INVALID_JSON = "The selected JSON file is not a valid HCQ document."
NO_QUEUES = "The run list is empty."
